Task_1_2_2
Tretiakovv/oop pull request #4
Opened 2022-10-09 15:11 UTC by Tretiakovv

Need to create a Generic-Tree class, which will implemets a Collection intercase.

2022-10-16 20:32 UTC, molo4evan commented on task_1_2_2/src/main/java/ru/nsu/fit/tretyakov/Tree.java
> +    public Tree(int size, T data) {
А зачем size? Он же 1

2022-10-16 20:32 UTC, molo4evan commented on task_1_2_2/src/main/java/ru/nsu/fit/tretyakov/Tree.java
> +    public Tree(int size, T data) {
Хотелось бы еще иметь возможность создать пустое дерево

2022-10-16 20:32 UTC, molo4evan commented on task_1_2_2/src/main/java/ru/nsu/fit/tretyakov/Tree.java
> +public class Tree<T> implements Collection<T> {
javadocs?

2022-10-16 20:32 UTC, molo4evan commented on task_1_2_2/src/main/java/ru/nsu/fit/tretyakov/Tree.java
> +    private Node<T> addRecursive(Node<T> node, T data) {
Дерево бинарное? Отрази в джавадоках

2022-10-16 20:32 UTC, molo4evan commented on task_1_2_2/src/main/java/ru/nsu/fit/tretyakov/Tree.java
> +                maxDepth = node.depth;
Зачем?

2022-10-16 20:33 UTC, molo4evan requested changes
41% покрытия, доработай тесты

2022-10-16 20:34 UTC, molo4evan commented on task_1_2_2/src/main/java/ru/nsu/fit/tretyakov/Tree.java
> +    private Node<T> removeRecursive(Node<T> curNode, T data) {
Очень замороченный код, сейчас не вывожу понять, что тут у тебя происходит, закончу проверять утром

2022-10-17 04:03 UTC, Tretiakovv commented on task_1_2_2/src/main/java/ru/nsu/fit/tretyakov/Tree.java
> +    public Tree(int size, T data) {
А что плохого в том, чтобы я хранил количество узлов дерева в этом поле?

2022-10-22 11:41 UTC, molo4evan commented on task_1_2_2/src/main/java/ru/nsu/fit/tretyakov/Tree.java
> +    public Tree(int size, T data) {
Речь не про поле, а про параметр конструктора. В какой ситуации тебе нужно передавать, скажем, size = 5? Зачем делать дерево размера 5, в котором фактически 1 элемент?

2022-10-22 11:47 UTC, molo4evan commented on task_1_2_2/src/main/java/ru/nsu/fit/tretyakov/Tree.java
> +    public static class TreeIterator<T> implements Iterator<T> {
Добавь еще ,пожалуйста, итератор в глубину

2022-10-22 11:47 UTC, molo4evan commented on task_1_2_2/src/main/java/ru/nsu/fit/tretyakov/Tree.java
> +            if (curNode.father != null) {
Удаление идет со всем поддеревом? Тогда стоит хотя бы отразить это в javadocs метода и итератора.

(По-хорошему, странно удалять сразу пачку элементов, а не 1 с перецеплением потомков)

2022-10-22 11:47 UTC, molo4evan commented on task_1_2_2/src/main/java/ru/nsu/fit/tretyakov/Tree.java
> +    public static class TreeIterator<T> implements Iterator<T> {
Не вижу поддержки ConcurrentModificationException, рассказывал на паре ,см. fail fast iterators

2022-10-23 05:58 UTC, Tretiakovv commented on task_1_2_2/src/main/java/ru/nsu/fit/tretyakov/Tree.java
> +            if (curNode.father != null) {
В изначальном варианте удаление было реализовано удаление с перецепливанием потомков, но реализация довольно сложная, так как нужно было учесть много ключевых моментов: удаление корня, удаление листа, удаление промежуточного узла. Каждый кейс реализовывался отдельно. Спросил у ребят, как они сделали — многие просто удаляют поддерево, так как пользователь знает, где находится какое поддерево и он сам должен контролировать структуру дерева. Джавадоки напишу!

2022-10-24 02:35 UTC, molo4evan commented on task_1_2_2/src/main/java/ru/nsu/fit/tretyakov/Tree.java
> +        public void remove() throws NullPointerException {
Тоже стоит изменять modCount

2022-10-24 03:07 UTC, merged